# Generated by Django 4.0.3 on 2022-11-29 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_remove_entry_profile_entry_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='pub_date',
        ),
    ]
