# Generated by Django 4.0.3 on 2022-12-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_alter_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(verbose_name='Publish Date'),
        ),
    ]
