# Generated by Django 4.0.3 on 2022-12-22 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_alter_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 21), verbose_name='Publish Date'),
        ),
    ]
