# Generated by Django 4.0.3 on 2023-01-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_alter_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Publish Date'),
        ),
    ]
