# Generated by Django 4.0.3 on 2023-01-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_alter_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='routine',
            field=models.CharField(max_length=500),
        ),
    ]
