# Generated by Django 4.0.3 on 2022-11-29 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_entry_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='profile',
        ),
        migrations.AddField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(default=datetime.date(2022, 11, 28)),
        ),
    ]
