# Generated by Django 4.0.3 on 2022-11-29 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_remove_entry_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(default=datetime.date(2022, 11, 28)),
        ),
    ]
